apiVersion: skaffold/v1beta2
kind: Config
build:
    local:
        push: false
    artifacts:
        -   image: aparnabhure/multi-client
            context: client 
            docker:
                dockerfile: Dockerfile.dev
            sync:
                '**/*.js': .
                '**/*.css': .
                '**/*.html': .
deploy:
    kubectl:
        manifests:
            - k8/client-deployment.yaml
            - k8/server-deployment.yaml
            - k8/worker-deployment.yaml
            - k8s/server-cluster-ip-service.yaml
            - k8s/client-cluster-ip-service.yaml       